config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'

  resources :home, :categories
  
  namespace :admin do
    resources :dashboard, :roles, :users, :categories, :posts, :coins
  end
  
  get '/:id' => 'categories#index', :as => 'danh-muc'
  get '/:cat_id/:id' => 'categories#show', :as => 'chi-tiet'
  
  

end

app/models/category.rb
class Category < ApplicationRecord
    include FriendlyId
    
    has_many :posts
    friendly_id :name, use:[:slugged]
    
    def normalize_friendly_id(input)
        input.to_slug.normalize(transliterations: :vietnamese).to_s
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  #before_filter :verify_logged
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.created_by = "Admin"
    @category.updated_by = "Admin"
    @category.delete_flag = 0
    if @category.parent_id.nil?
      @category.parent_id = 0
    end
    
    if @category.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def index
    @categories = Category.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def category_params
      params.require(:category).permit(:name, :description, :created_by, :updated_by, :delete_flag, :parent_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @firstCoin = Coin.order("created_at DESC").offset(0).first
    @id = params[:id].downcase
    
    unless @id.nil?
      @name = getCategoryName(@id)
    else
      redirect_to root_path
      return
    end
    
    @id = Category.find_by(name: @name).id
    @firstPost = Post.where(category_id: @id).order("created_at DESC").offset(0).first
    @secondPosts = Post.where(category_id: @id).order("created_at DESC").offset(1).first(3)
    @listPost = Post.where(category_id: @id).order("created_at DESC").offset(4).all
  end

  def show
    if params["format"] == "html"
      @cat_id = params[:cat_id].downcase
      unless @cat_id.nil?
        @catName = getCategoryName(@cat_id)
        @catId = Category.find_by(name: @catName).id
        
        @listTop3PostInCat = Post.where(category_id: @catId).order("created_at DESC").offset(0).first(3)
        
        @postId = params[:id]
        
        unless @postId.nil?
          if Post.friendly.exists_by_friendly_id?(@postId)
            @post = Post.friendly.find(@postId)
          else
            redirect_to root_path
            return  
          end
        else
          redirect_to root_path
          return  
        end
      else
        redirect_to root_path
        return
      end
    else
      redirect_to root_path
      return
    end
  end
  
  def getCategoryName(catName)
    if catName == "ico"
      return "ICO"
    elsif catName == "blockchain"
      return "BLOCKCHAIN"
    elsif catName == "fintech"
      return "FINTECH"
    elsif catName == "cryptocurrency"
      return "CRYPTOCURRENCY"
    elsif catName == "bieu-do-coin"
      return "BIỂU ĐỒ COIN"
    elsif catName == "chung-khoan"
      return "CHỨNG KHOÁN"
    elsif catName == "cong-nghe"
      return "CÔNG NGHỆ"
    elsif catName == "kinh-doanh"
      return "KINH DOANH"
    else
      redirect_to root_path
      return
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/create.html.erb
<h1>Admin::Categories#create</h1>
<p>Find me in app/views/admin/categories/create.html.erb</p>

app/views/admin/categories/destroy.html.erb
<h1>Admin::Categories#destroy</h1>
<p>Find me in app/views/admin/categories/destroy.html.erb</p>

app/views/admin/categories/edit.html.erb
<h1>Admin::Categories#edit</h1>
<p>Find me in app/views/admin/categories/edit.html.erb</p>

app/views/admin/categories/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Quản lý Danh Mục <small></small></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Tìm kiếm">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <%= render 'partials/admin/notification' %>
          <%= link_to "Thêm mới", new_admin_category_path, class: "btn btn-success pull-right" %>
          
          <div class="x_content">
             
            <div class="table-responsive">
              <table class="table table-striped jambo_table bulk_action">
                <thead>
                  <tr class="headings">
                    <th>
                      <input type="checkbox" id="check-all" class="flat">
                    </th>
                    <th class="column-title">ID </th>
                    <th class="column-title">Tên Danh Mục</th>
                    <th class="column-title">Danh Mục Cha</th>
                    <th class="column-title">Mô tả</th>
                    <th class="column-title">Ngày Tạo</th>
                    <th class="column-title">Ngày cập nhật</th>
                    <th class="column-title no-link last"><span class="nobr">Actions</span>
                    </th>
                  </tr>
                </thead>

                <tbody>
                  <% @categories.each do |f| %>
                    <tr class="even pointer">
                      <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=" "><%= f.id %></td>
                      <td class=" "><%= f.name %> </td>
                      <td class=" "><%= Category.find(f.parent_id).name if f.parent_id != 0 %></td>
                      <td class=" "><%= f.description %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %> </td>
                      <td class=" "><%= link_to "Cập Nhật", edit_admin_category_path(f), class:'btn btn-primary' %> 
                        <%= link_to "Xóa", admin_category_path(f), class:'btn btn-danger', method: :delete, data: {confirm: "Bạn có muốn xóa thông tin này ???"} %>
                      </td>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Quản lý Danh Mục<small></small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <%= form_for [:admin, @category], :html => {:class => 'form-horizontal form-label-left'} do |f| %>
              </p>
              <span class="section">Thêm Danh Mục</span>

              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên<span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :name, class:'form-control col-md-7 col-xs-12', 'data-validate-left-range' =>'5', 'data-validate-words' =>'1', placeholder:'', 'required' => 'required' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Mô tả<span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :description, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="item form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="role">Danh Mục Cha <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.select :parent_id, Category.where(delete_flag: 0).all.collect {|x| [x.name, x.id]},{:include_blank => "-- Danh Mục Cha --"}, class:'form-control' %>
                  </div>
              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= link_to "Hủy", admin_categories_path, class:'btn btn-primary' %>
                  <%= f.submit "OK", class:'btn btn-success' %>
                </div>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<h1>Admin::Categories#show</h1>
<p>Find me in app/views/admin/categories/show.html.erb</p>

app/views/admin/categories/update.html.erb
<h1>Admin::Categories#update</h1>
<p>Find me in app/views/admin/categories/update.html.erb</p>