config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'

  resources :home, :categories
  
  namespace :admin do
    resources :dashboard, :roles, :users, :categories, :posts, :coins
  end
  
  get '/:id' => 'categories#index', :as => 'danh-muc'
  get '/:cat_id/:id' => 'categories#show', :as => 'chi-tiet'
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    include FriendlyId
    
    has_many :posts
    friendly_id :name, use:[:slugged]
    
    def normalize_friendly_id(input)
        input.to_slug.normalize(transliterations: :vietnamese).to_s
    end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/coin.rb
class Coin < ApplicationRecord
    include FriendlyId
    
    has_attached_file :image
    friendly_id :name, use:[:slugged]
    
    validates_attachment :image,
        content_type: { content_type: /\Aimage\/.*\z/ },
        size: { less_than: 2.megabyte }
        
        
    def normalize_friendly_id(input)
        input.to_slug.normalize(transliterations: :vietnamese).to_s
    end
end

app/models/post.rb
class Post < ApplicationRecord
    include FriendlyId
    
    has_attached_file :image
    friendly_id :title, use:[:slugged]
    belongs_to :category
    
    validates_attachment :image,
        content_type: { content_type: /\Aimage\/.*\z/ },
        size: { less_than: 5.megabyte }
        
        
    def normalize_friendly_id(input)
        input.to_slug.normalize(transliterations: :vietnamese).to_s
    end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    belongs_to :role
    before_create :encrypted_password
    
    def has_password?(submitted_password)
        encrypt_password == encrypt(submitted_password)
    end
    
    def self.authenticate(name, submitted_password)
        user = User.find_by(email: name)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end
    
    def self.isUserValid?(email)
        user = User.find_by(email: email)
        return true if user.nil?
        return false unless user.nil?
    end
    
    private
        def encrypted_password
            #generate a unique salt if it is a new user
            self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
            
            #encrypt the password and store that in the ecrypted_password field
            self.encrypt_password = encrypt(password)
        end
        
        def encrypt(pass)
            Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
        end
end

app/controllers/admin/coins_controller.rb
class Admin::CoinsController < Admin::ApplicationController
  def new
    @coin = Coin.new
  end

  def create
    @coin = Coin.new(coin_params)
    @coin.created_by = "Admin"
    @coin.updated_by = "Admin"
    @coin.delete_flag = 0
    if @coin.save
      redirect_to admin_coins_path
    else
      render :new
    end
    
  end

  def edit
  end

  def update
  end

  def index
    @coins = Coin.where(delete_flag: 0).order('created_at DESC')
  end

  def show
  end

  def destroy
  end
  
  private
    def coin_params
      params.require(:coin).permit(:name, :image, :website, :ico_from, :ico_to, :industry, :slug)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  
  def new
    @user = User.new
  end

  def create
    
    if params["email"].nil?
      @user = User.new(user_params)
      @user.created_by = "Admin"
      @user.updated_by = "Admin"
    else
      @user = User.new
      @user.email = params["email"]
      @user.password = params["password"]
      if @user.role_id.nil?
        @user.role_id = 2
      end
      @user.created_by = "system"
      @user.updated_by = "system"
    end
    
    #generate Token
    
    #o = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
    #@user.token = (0...32).map { o[rand(o.length)] }.join
    
    #@user.provider = "Website"
    @user.delete_flag = 0
    
    #TODO: 
    #kiem tra user da ton tai hay chua (name/email/sdt)
    if User.isUserValid?(@user.name)
      if @user.save
          flash[:success] = 'Tạo mới thành công'
          redirect_to admin_users_path
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   
  end

  def index
    @users = User.where(delete_flag: 0).all
  end

  def show
  end

  def destroy
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :role_id,:email, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'application'
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @firstCoin = Coin.order("created_at DESC").offset(0).first
    @id = params[:id].downcase
    
    unless @id.nil?
      @name = getCategoryName(@id)
    else
      redirect_to root_path
      return
    end
    
    @id = Category.find_by(name: @name).id
    @firstPost = Post.where(category_id: @id).order("created_at DESC").offset(0).first
    @secondPosts = Post.where(category_id: @id).order("created_at DESC").offset(1).first(3)
    @listPost = Post.where(category_id: @id).order("created_at DESC").offset(4).all
  end

  def show
    if params["format"] == "html"
      @cat_id = params[:cat_id].downcase
      unless @cat_id.nil?
        @catName = getCategoryName(@cat_id)
        @catId = Category.find_by(name: @catName).id
        
        @listTop3PostInCat = Post.where(category_id: @catId).order("created_at DESC").offset(0).first(3)
        
        @postId = params[:id]
        
        unless @postId.nil?
          if Post.friendly.exists_by_friendly_id?(@postId)
            @post = Post.friendly.find(@postId)
          else
            redirect_to root_path
            return  
          end
        else
          redirect_to root_path
          return  
        end
      else
        redirect_to root_path
        return
      end
    else
      redirect_to root_path
      return
    end
  end
  
  def getCategoryName(catName)
    if catName == "ico"
      return "ICO"
    elsif catName == "blockchain"
      return "BLOCKCHAIN"
    elsif catName == "fintech"
      return "FINTECH"
    elsif catName == "cryptocurrency"
      return "CRYPTOCURRENCY"
    elsif catName == "bieu-do-coin"
      return "BIỂU ĐỒ COIN"
    elsif catName == "chung-khoan"
      return "CHỨNG KHOÁN"
    elsif catName == "cong-nghe"
      return "CÔNG NGHỆ"
    elsif catName == "kinh-doanh"
      return "KINH DOANH"
    else
      redirect_to root_path
      return
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @firstPost = Post.order("created_at DESC").offset(0).first
    @secondPosts = Post.order("created_at DESC").offset(1).first(3)
    @listPost = Post.order("created_at DESC").offset(4).all
    @firstCoin = Coin.order("created_at DESC").offset(0).first
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/coins_helper.rb
module Admin::CoinsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    using HomeHelper
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def replace_text(text)
        if text.length > 350
            return text[0..350]+"..."
        else
            return text
        end
    end
end

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Quản lý Người Dùng <small></small></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Tìm kiếm">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <%= render 'partials/admin/notification' %>
          <%= link_to "Thêm Người dùng" , new_admin_user_path, class: "btn btn-success pull-right" %>
          
          <div class="x_content">
             
            <div class="table-responsive">
              <table class="table table-striped jambo_table bulk_action">
                <thead>
                  <tr class="headings">
                    <th><input type="checkbox" id="check-all" class="flat"></th>
                    <th class="column-title">ID </th>
                    <th class="column-title">Email</th>
                    <th class="column-title">Quyền</th>
                    <th class="column-title">Ngày cập nhật</th>
                    <th class="column-title no-link last"><span class="nobr">Action</span></th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |f| %>
                    <tr class="even pointer">
                      <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=" "><%= f.id %></td>
                      <td class=" "><%= f.email %></td>
                      <td class=" "><%= f.role.name %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %> </td>
                      <td class=" ">
                        <%= link_to "Cập nhật", edit_admin_user_path(f), class:'btn btn-primary' %> 
                        <%= link_to "Xóa", admin_user_path(f), class:'btn btn-danger', method: :delete, data: {confirm: "Bạn có muốn xóa Thành Viên này ???"} %>
                      </td>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Quản lý Người dùng<small></small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <%= form_for [:admin, @user], :html => {:class => 'form-horizontal form-label-left'} do |f| %>
              </p>
              <span class="section">Thêm mới Người dùng</span>

              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên<span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :name, class:'form-control col-md-7 col-xs-12', 'data-validate-left-range' =>'6', 'data-validate-words' =>'1', placeholder:'', 'required' => 'required' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :email, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="item form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="role">Quyền <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.select :role_id, Role.where(delete_flag: 0).all.collect {|x| [x.name, x.id]},{:include_blank => "-- Quyền --"}, class:'form-control' %>
                  </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="password"><%= t("laluna.label.password") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.password_field :password, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= link_to "Hủy", new_admin_role_path, class:'btn btn-primary' %>
                  <%= f.submit "OK", class:'btn btn-success' %>
                </div>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>