config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'

  resources :home, :categories
  
  namespace :admin do
    resources :dashboard, :roles, :users, :categories, :posts, :coins
  end
  
  get '/:id' => 'categories#index', :as => 'danh-muc'
  get '/:cat_id/:id' => 'categories#show', :as => 'chi-tiet'
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    include FriendlyId
    
    has_many :posts
    friendly_id :name, use:[:slugged]
    
    def normalize_friendly_id(input)
        input.to_slug.normalize(transliterations: :vietnamese).to_s
    end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/coin.rb
class Coin < ApplicationRecord
    include FriendlyId
    
    has_attached_file :image
    friendly_id :name, use:[:slugged]
    
    validates_attachment :image,
        content_type: { content_type: /\Aimage\/.*\z/ },
        size: { less_than: 2.megabyte }
        
        
    def normalize_friendly_id(input)
        input.to_slug.normalize(transliterations: :vietnamese).to_s
    end
end

app/models/post.rb
class Post < ApplicationRecord
    include FriendlyId
    
    has_attached_file :image
    friendly_id :title, use:[:slugged]
    belongs_to :category
    
    validates_attachment :image,
        content_type: { content_type: /\Aimage\/.*\z/ },
        size: { less_than: 5.megabyte }
        
        
    def normalize_friendly_id(input)
        input.to_slug.normalize(transliterations: :vietnamese).to_s
    end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    belongs_to :role
    before_create :encrypted_password
    
    def has_password?(submitted_password)
        encrypt_password == encrypt(submitted_password)
    end
    
    def self.authenticate(name, submitted_password)
        user = User.find_by(email: name)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end
    
    def self.isUserValid?(email)
        user = User.find_by(email: email)
        return true if user.nil?
        return false unless user.nil?
    end
    
    private
        def encrypted_password
            #generate a unique salt if it is a new user
            self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
            
            #encrypt the password and store that in the ecrypted_password field
            self.encrypt_password = encrypt(password)
        end
        
        def encrypt(pass)
            Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'application'
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @firstCoin = Coin.order("created_at DESC").offset(0).first
    @id = params[:id].downcase
    
    unless @id.nil?
      @name = getCategoryName(@id)
    else
      redirect_to root_path
      return
    end
    
    @id = Category.find_by(name: @name).id
    @firstPost = Post.where(category_id: @id).order("created_at DESC").offset(0).first
    @secondPosts = Post.where(category_id: @id).order("created_at DESC").offset(1).first(3)
    @listPost = Post.where(category_id: @id).order("created_at DESC").offset(4).all
  end

  def show
    if params["format"] == "html"
      @cat_id = params[:cat_id].downcase
      unless @cat_id.nil?
        @catName = getCategoryName(@cat_id)
        @catId = Category.find_by(name: @catName).id
        
        @listTop3PostInCat = Post.where(category_id: @catId).order("created_at DESC").offset(0).first(3)
        
        @postId = params[:id]
        
        unless @postId.nil?
          if Post.friendly.exists_by_friendly_id?(@postId)
            @post = Post.friendly.find(@postId)
          else
            redirect_to root_path
            return  
          end
        else
          redirect_to root_path
          return  
        end
      else
        redirect_to root_path
        return
      end
    else
      redirect_to root_path
      return
    end
  end
  
  def getCategoryName(catName)
    if catName == "ico"
      return "ICO"
    elsif catName == "blockchain"
      return "BLOCKCHAIN"
    elsif catName == "fintech"
      return "FINTECH"
    elsif catName == "cryptocurrency"
      return "CRYPTOCURRENCY"
    elsif catName == "bieu-do-coin"
      return "BIỂU ĐỒ COIN"
    elsif catName == "chung-khoan"
      return "CHỨNG KHOÁN"
    elsif catName == "cong-nghe"
      return "CÔNG NGHỆ"
    elsif catName == "kinh-doanh"
      return "KINH DOANH"
    else
      redirect_to root_path
      return
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @firstPost = Post.order("created_at DESC").offset(0).first
    @secondPosts = Post.order("created_at DESC").offset(1).first(3)
    @listPost = Post.order("created_at DESC").offset(4).all
    @firstCoin = Coin.order("created_at DESC").offset(0).first
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/coins_helper.rb
module Admin::CoinsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    using HomeHelper
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def replace_text(text)
        if text.length > 350
            return text[0..350]+"..."
        else
            return text
        end
    end
end

app/views/layouts/admin/admin.html.erb
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tài Chính Số | Hệ Thống Quản Lý</title>  
  <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        
        <%= render 'partials/admin/menu' %>

        <%= render 'partials/admin/topnavigation' %>
        
        <!-- page content -->
        <%= yield %>
        <!-- /page content -->
        <%= render 'partials/admin/footer' %>
      </div>
    </div>
  </body>
</body> 
</html>

app/views/layouts/application.html.erb
<html>
  <head>
  	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
  	<!-- Meta, title, CSS, favicons, etc. -->
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="profile" href="http://gmpg.org/xfn/11">		
	<link rel="shortcut icon" href="https://potato.fsoft.com.vn/wp-content/themes/smart-magazine/favicon.ico">
	<title>Tài Chính Số</title>
    <link rel="dns-prefetch" href="https://s.w.org/">

    <!-- Custom Theme files -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="archive category group-blog">
	<%= render "partials/navbar" %>

    <div id="content" class="container" data-attr="wrapper-layout-content">
	    <%= yield %>
    </div>

    <div id="footer" class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-xs-12">
                    <a href="/">                        
                        <%= image_tag "logo-footer-potato-xmas.png", width: "90%" %>
                    </a>
                </div>
                <div class="col-md-9 col-xs-12 potato-footer-content-right">
                    <div class="potato-think"> 
                        Think Fintech, Think TaiChinhSo
                    </div>
                    <div class="potato-des"> 
                        Chuyên trang về công nghệ Tài Chính, các chia sẻ về các công nghệ mới nhất.                    
                    </div>

                    <ul class="col-md-12 potato-footer-menu">
                        <li class="col-md-2">
                        	<a href="/">Home</a>
                        </li>
                        <li class="col-md-2">
                        	<a href="/fintech">Fintech</a>
                        </li>
                        <li class="col-md-2">
                        	<a href="/ico">ICO</a>
                        </li>
                        <li class="col-md-2">
                        	<a href="/chung-khoan">Chứng Khoán</a>
                        </li>
                        <li class="col-md-2">
                        	<a href="/cong-nghe">Công Nghệ</a>
                        </li>
                        <li class="col-md-2">
                        	<a href="/kinh-doanh">Kinh Doanh</a>
                        </li>
                    </ul>
                    <div class="potato-footer-line"></div>
                    <div class="copywrite">
                        <div class="col-footer-logo">
                            <span class="potato-copyright">    						
    							2018 © Tài Chính Số. All Rights Reserved.    							
                            </span>
                        </div>
                    </div>
                </div>
            </div>
			<div id="toTop" style="display: block;">
				<i class="glyphicon glyphicon-chevron-up"></i>
			</div>
		</div>
	</div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="potato-middle-header navbar primary">
    <div class="container potato-header-border">
        <div class="navbar-header">
            <a class="navbar-brand potato-logo" href="/">
            	<h1 class="logo-text">Tài Chính Số</h1>
            	<small class="slogan">
            		Chúng tôi nói về FinTech
            	</small>
            </a>
        </div>

        <div class="h-border navbar-collapse is_dwqa">
            <ul class="nav navbar-nav navbar-right">
            	<li class="li-search-form">
               		<form class="navbar-form pull-right" role="search" method="get" action="#">
	                    <div class="input-group search-input">
	                        <input type="text" class="form-control" placeholder="Tìm Kiếm" value="" name="s" title="Search for:">
	                        <span class="input-group-btn">
	                        	<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
	                      	</span>
	                    </div>
	                </form>
                </li>								
            </ul>
			
			<div class="top-navigation navbar-collapse">
				<div class="container-menu">
					<ul class="navigation primary">
						<div class="menu-top-container">
							<ul id="primary-menu" class="sf-menu">
								<li class="menu-item menu-item-type-custom menu-item-object-custom">
									<a href="/">HOME</a>
								</li>
								<li class="menu-item menu-item-type-taxonomy menu-item-object-category">
									<a href="/fintech">FINTECH</a>
								</li>
								<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">
									<a href="/blockchain">BLOCKCHAIN</a>										
								</li>
								<li class="menu-item menu-item-type-taxonomy menu-item-object-category">
									<a href="/cryptocurrency">CRYPTOCURRENCY</a>
									<ul class="sub-menu">
										<li class="menu-item menu-item-type-taxonomy menu-item-object-category">
											<a href="/ico">ICO</a>
										</li>
										<li class="menu-item menu-item-type-custom menu-item-object-custom">
											<a href="/bieu-do-coin">BIỂU ĐỒ COIN</a>
										</li>
									</ul>
								</li>
								<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">
									<a href="/chung-khoan">CHỨNG KHOÁN</a>										
								</li>
								<li class="menu-item menu-item-type-taxonomy menu-item-object-category">
									<a href="/cong-nghe">CÔNG NGHỆ</a>
								</li>
								<li class="menu-item menu-item-type-taxonomy menu-item-object-category">
									<a href="/kinh-doanh">KINH DOANH</a>
								</li>
								<li class="menu-item menu-item-type-taxonomy menu-item-object-category">
									<a href="#">LIÊN HỆ</a>
								</li>																		
							</ul>
						</div>
					</ul>
				</div>
			</div>
        </div>
        <!--/.nav-collapse -->
    </div>    
</div>

app/views/partials/admin/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    A Product of <a href="https://taichinhso.com">Tài Chính Số</a> © 2018
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

app/views/partials/admin/_menu.html.erb
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="#" class="site_title"><i class="fa fa-moon-o"></i> <span>TCS</span></a>
    </div>
    
    <div class="clearfix"></div>
    
    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <%= image_tag("img.jpg", class: "img-circle profile_img", alt: "...") %>
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2>YLM1</h2>
      </div>
    </div>
    <!-- /menu profile quick info -->
    
    <br />
    
    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>Thông Tin</h3>
        <ul class="nav side-menu">
          
          <li><a><i class="fa fa-home"></i> Thông Tin Chung <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li>
                <%= link_to "Dashboard", "#" %>
              </li>
            </ul>
          </li>
          <li><a><i class="fa fa-desktop"></i> Quản lý<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to "Quản lý Người Dùng", admin_users_path %></li>
              <li><%= link_to "Quản lý Quyền", admin_roles_path %></li>
              <li><%= link_to "Quản lý Danh Mục", "#" %></li>
              <li><%= link_to "Quản lý Bài Viết", "#" %></li>
              <li><%= link_to "Quản lý ICO", "#" %></li>
            </ul>
          </li>
        </ul>
      </div>
    
    </div>
    <!-- /sidebar menu -->
    
    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>
      <%= link_to "" do %>
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      <% end %>
    </div>
    <!-- /menu footer buttons -->
    </div>
</div>

app/views/partials/admin/_notification.html.erb
<% if flash[:success] %>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <strong><%=h flash[:success] %></strong>
    </div>
<% elsif flash[:error] %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= flash[:error].html_safe  %>
    </div>
<% elsif flash[:userInfo] && controller.controller_name == "orders" %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= flash[:userInfo].html_safe  %>
    </div>
<% end %>

app/views/partials/admin/_topnavigation.html.erb
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag("img.jpg",alt:"") %>
            YLM1
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="#"> Thông tin cá nhân</a></li>
            <!--<li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>-->
            <li>
              <%= link_to "#" do %>
                Đăng Xuất<i class="fa fa-sign-out pull-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
        <!--<li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image">
                  <%= image_tag("img.jpg", alt: "Profile Image") %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image">
                  <%= image_tag("img.jpg", alt: "Profile Image") %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><%= image_tag("img.jpg", alt: "Profile Image") %></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><%= image_tag("img.jpg", alt: "Profile Image") %></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>-->
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->